export type TimeZoneAlias = {
  timeZoneId: string;
  city: string;
  district?: string;
  country?: string;
  searchTerms?: string[];
  primary?: boolean;
};

export const TIMEZONE_ALIASES: TimeZoneAlias[] = [
  { timeZoneId: 'Africa/Abidjan', city: 'Abidjan', country: "Cote d'Ivoire", primary: true },
  { timeZoneId: 'Africa/Accra', city: 'Accra', country: 'Ghana', primary: true },
  { timeZoneId: 'Africa/Addis_Ababa', city: 'Addis Ababa', country: 'Ethiopia', primary: true },
  { timeZoneId: 'Africa/Algiers', city: 'Algiers', country: 'Algeria', primary: true },
  { timeZoneId: 'Africa/Cairo', city: 'Cairo', country: 'Egypt', primary: true },
  { timeZoneId: 'Africa/Casablanca', city: 'Casablanca', country: 'Morocco', primary: true },
  { timeZoneId: 'Africa/Dakar', city: 'Dakar', country: 'Senegal', primary: true },
  {
    timeZoneId: 'Africa/Dar_es_Salaam',
    city: 'Dar es Salaam',
    country: 'Tanzania',
    primary: true,
  },
  {
    timeZoneId: 'Africa/Johannesburg',
    city: 'Johannesburg',
    country: 'South Africa',
    primary: true,
  },
  { timeZoneId: 'Africa/Khartoum', city: 'Khartoum', country: 'Sudan', primary: true },
  { timeZoneId: 'Africa/Lagos', city: 'Lagos', country: 'Nigeria', primary: true },
  { timeZoneId: 'Africa/Nairobi', city: 'Nairobi', country: 'Kenya', primary: true },
  { timeZoneId: 'Africa/Tripoli', city: 'Tripoli', country: 'Libya', primary: true },
  { timeZoneId: 'Africa/Tunis', city: 'Tunis', country: 'Tunisia', primary: true },
  {
    timeZoneId: 'America/Anchorage',
    city: 'Anchorage',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Chicago',
    city: 'Chicago',
    district: 'Illinois',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Denver',
    city: 'Denver',
    district: 'Colorado',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Detroit',
    city: 'Detroit',
    district: 'Michigan',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'Los Angeles',
    district: 'California',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/New_York',
    city: 'New York',
    district: 'New York State',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Phoenix',
    city: 'Phoenix',
    district: 'Arizona',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Juneau',
    city: 'Juneau',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Boise',
    city: 'Boise',
    district: 'Idaho',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Sitka',
    city: 'Sitka',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Metlakatla',
    city: 'Metlakatla',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Nome',
    city: 'Nome',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Adak',
    city: 'Adak',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Yakutat',
    city: 'Yakutat',
    district: 'Alaska',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Menominee',
    city: 'Menominee',
    district: 'Michigan',
    country: 'United States',
    primary: true,
  },
  {
    timeZoneId: 'America/Toronto',
    city: 'Toronto',
    district: 'Ontario',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/Vancouver',
    city: 'Vancouver',
    district: 'British Columbia',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/Edmonton',
    city: 'Edmonton',
    district: 'Alberta',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/Winnipeg',
    city: 'Winnipeg',
    district: 'Manitoba',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/Halifax',
    city: 'Halifax',
    district: 'Nova Scotia',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/St_Johns',
    city: 'St Johns',
    district: 'Newfoundland and Labrador',
    country: 'Canada',
    primary: true,
  },
  {
    timeZoneId: 'America/Mexico_City',
    city: 'Mexico City',
    country: 'Mexico',
    primary: true,
  },
  {
    timeZoneId: 'America/Argentina/Buenos_Aires',
    city: 'Buenos Aires',
    country: 'Argentina',
    primary: true,
  },
  { timeZoneId: 'America/Sao_Paulo', city: 'Sao Paulo', country: 'Brazil', primary: true },
  { timeZoneId: 'America/Santiago', city: 'Santiago', country: 'Chile', primary: true },
  { timeZoneId: 'America/Bogota', city: 'Bogota', country: 'Colombia', primary: true },
  { timeZoneId: 'America/Lima', city: 'Lima', country: 'Peru', primary: true },
  { timeZoneId: 'America/Caracas', city: 'Caracas', country: 'Venezuela', primary: true },
  { timeZoneId: 'America/La_Paz', city: 'La Paz', country: 'Bolivia', primary: true },
  { timeZoneId: 'America/Montevideo', city: 'Montevideo', country: 'Uruguay', primary: true },
  { timeZoneId: 'America/Asuncion', city: 'Asuncion', country: 'Paraguay', primary: true },
  { timeZoneId: 'America/Guayaquil', city: 'Guayaquil', country: 'Ecuador', primary: true },
  { timeZoneId: 'America/Guatemala', city: 'Guatemala City', country: 'Guatemala', primary: true },
  { timeZoneId: 'America/Managua', city: 'Managua', country: 'Nicaragua', primary: true },
  { timeZoneId: 'America/Costa_Rica', city: 'San Jose', country: 'Costa Rica', primary: true },
  { timeZoneId: 'America/Panama', city: 'Panama City', country: 'Panama', primary: true },
  { timeZoneId: 'America/Havana', city: 'Havana', country: 'Cuba', primary: true },
  { timeZoneId: 'America/Jamaica', city: 'Kingston', country: 'Jamaica', primary: true },
  {
    timeZoneId: 'America/Santo_Domingo',
    city: 'Santo Domingo',
    country: 'Dominican Republic',
    primary: true,
  },
  {
    timeZoneId: 'America/Port-au-Prince',
    city: 'Port-au-Prince',
    country: 'Haiti',
    primary: true,
  },
  {
    timeZoneId: 'America/Port_of_Spain',
    city: 'Port of Spain',
    country: 'Trinidad and Tobago',
    primary: true,
  },
  {
    timeZoneId: 'Pacific/Honolulu',
    city: 'Honolulu',
    district: 'Hawaii',
    country: 'United States',
    primary: true,
  },
  { timeZoneId: 'Europe/London', city: 'London', country: 'United Kingdom', primary: true },
  { timeZoneId: 'Europe/Dublin', city: 'Dublin', country: 'Ireland', primary: true },
  { timeZoneId: 'Europe/Paris', city: 'Paris', country: 'France', primary: true },
  { timeZoneId: 'Europe/Berlin', city: 'Berlin', country: 'Germany', primary: true },
  { timeZoneId: 'Europe/Rome', city: 'Rome', country: 'Italy', primary: true },
  { timeZoneId: 'Europe/Madrid', city: 'Madrid', country: 'Spain', primary: true },
  { timeZoneId: 'Europe/Lisbon', city: 'Lisbon', country: 'Portugal', primary: true },
  { timeZoneId: 'Europe/Amsterdam', city: 'Amsterdam', country: 'Netherlands', primary: true },
  { timeZoneId: 'Europe/Brussels', city: 'Brussels', country: 'Belgium', primary: true },
  { timeZoneId: 'Europe/Zurich', city: 'Zurich', country: 'Switzerland', primary: true },
  { timeZoneId: 'Europe/Vienna', city: 'Vienna', country: 'Austria', primary: true },
  { timeZoneId: 'Europe/Prague', city: 'Prague', country: 'Czech Republic', primary: true },
  { timeZoneId: 'Europe/Warsaw', city: 'Warsaw', country: 'Poland', primary: true },
  { timeZoneId: 'Europe/Stockholm', city: 'Stockholm', country: 'Sweden', primary: true },
  { timeZoneId: 'Europe/Oslo', city: 'Oslo', country: 'Norway', primary: true },
  { timeZoneId: 'Europe/Copenhagen', city: 'Copenhagen', country: 'Denmark', primary: true },
  { timeZoneId: 'Europe/Helsinki', city: 'Helsinki', country: 'Finland', primary: true },
  { timeZoneId: 'Europe/Athens', city: 'Athens', country: 'Greece', primary: true },
  { timeZoneId: 'Europe/Bucharest', city: 'Bucharest', country: 'Romania', primary: true },
  { timeZoneId: 'Europe/Budapest', city: 'Budapest', country: 'Hungary', primary: true },
  { timeZoneId: 'Europe/Sofia', city: 'Sofia', country: 'Bulgaria', primary: true },
  { timeZoneId: 'Europe/Kiev', city: 'Kyiv', country: 'Ukraine', primary: true },
  { timeZoneId: 'Europe/Istanbul', city: 'Istanbul', country: 'Turkey', primary: true },
  { timeZoneId: 'Europe/Moscow', city: 'Moscow', country: 'Russia', primary: true },
  { timeZoneId: 'Atlantic/Reykjavik', city: 'Reykjavik', country: 'Iceland', primary: true },
  { timeZoneId: 'Asia/Tokyo', city: 'Tokyo', country: 'Japan', primary: true },
  { timeZoneId: 'Asia/Seoul', city: 'Seoul', country: 'South Korea', primary: true },
  { timeZoneId: 'Asia/Shanghai', city: 'Shanghai', country: 'China', primary: true },
  { timeZoneId: 'Asia/Hong_Kong', city: 'Hong Kong', country: 'Hong Kong', primary: true },
  { timeZoneId: 'Asia/Singapore', city: 'Singapore', country: 'Singapore', primary: true },
  { timeZoneId: 'Asia/Bangkok', city: 'Bangkok', country: 'Thailand', primary: true },
  { timeZoneId: 'Asia/Jakarta', city: 'Jakarta', country: 'Indonesia', primary: true },
  { timeZoneId: 'Asia/Manila', city: 'Manila', country: 'Philippines', primary: true },
  { timeZoneId: 'Asia/Kuala_Lumpur', city: 'Kuala Lumpur', country: 'Malaysia', primary: true },
  { timeZoneId: 'Asia/Kolkata', city: 'Kolkata', country: 'India', primary: true },
  { timeZoneId: 'Asia/Karachi', city: 'Karachi', country: 'Pakistan', primary: true },
  { timeZoneId: 'Asia/Dhaka', city: 'Dhaka', country: 'Bangladesh', primary: true },
  { timeZoneId: 'Asia/Kathmandu', city: 'Kathmandu', country: 'Nepal', primary: true },
  { timeZoneId: 'Asia/Colombo', city: 'Colombo', country: 'Sri Lanka', primary: true },
  { timeZoneId: 'Asia/Kabul', city: 'Kabul', country: 'Afghanistan', primary: true },
  { timeZoneId: 'Asia/Dubai', city: 'Dubai', country: 'United Arab Emirates', primary: true },
  { timeZoneId: 'Asia/Riyadh', city: 'Riyadh', country: 'Saudi Arabia', primary: true },
  { timeZoneId: 'Asia/Tehran', city: 'Tehran', country: 'Iran', primary: true },
  { timeZoneId: 'Asia/Jerusalem', city: 'Jerusalem', country: 'Israel', primary: true },
  { timeZoneId: 'Asia/Qatar', city: 'Doha', country: 'Qatar', primary: true },
  { timeZoneId: 'Asia/Kuwait', city: 'Kuwait City', country: 'Kuwait', primary: true },
  { timeZoneId: 'Asia/Baghdad', city: 'Baghdad', country: 'Iraq', primary: true },
  { timeZoneId: 'Asia/Amman', city: 'Amman', country: 'Jordan', primary: true },
  { timeZoneId: 'Asia/Beirut', city: 'Beirut', country: 'Lebanon', primary: true },
  { timeZoneId: 'Asia/Damascus', city: 'Damascus', country: 'Syria', primary: true },
  { timeZoneId: 'Asia/Muscat', city: 'Muscat', country: 'Oman', primary: true },
  { timeZoneId: 'Asia/Yangon', city: 'Yangon', country: 'Myanmar', primary: true },
  { timeZoneId: 'Asia/Ho_Chi_Minh', city: 'Ho Chi Minh City', country: 'Vietnam', primary: true },
  { timeZoneId: 'Asia/Taipei', city: 'Taipei', country: 'Taiwan', primary: true },
  { timeZoneId: 'Australia/Sydney', city: 'Sydney', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Melbourne', city: 'Melbourne', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Brisbane', city: 'Brisbane', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Perth', city: 'Perth', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Adelaide', city: 'Adelaide', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Darwin', city: 'Darwin', country: 'Australia', primary: true },
  { timeZoneId: 'Australia/Hobart', city: 'Hobart', country: 'Australia', primary: true },
  { timeZoneId: 'Pacific/Auckland', city: 'Auckland', country: 'New Zealand', primary: true },
  { timeZoneId: 'Pacific/Fiji', city: 'Suva', country: 'Fiji', primary: true },
  {
    timeZoneId: 'Pacific/Port_Moresby',
    city: 'Port Moresby',
    country: 'Papua New Guinea',
    primary: true,
  },
  { timeZoneId: 'Pacific/Apia', city: 'Apia', country: 'Samoa', primary: true },
  { timeZoneId: 'Pacific/Guam', city: 'Guam', country: 'United States', primary: true },
  { timeZoneId: 'Africa/Accra', city: 'Kumasi', country: 'Ghana' },
  { timeZoneId: 'Africa/Addis_Ababa', city: 'Dire Dawa', country: 'Ethiopia' },
  { timeZoneId: 'Africa/Algiers', city: 'Oran', country: 'Algeria' },
  { timeZoneId: 'Africa/Cairo', city: 'Alexandria', country: 'Egypt' },
  { timeZoneId: 'Africa/Casablanca', city: 'Rabat', country: 'Morocco' },
  { timeZoneId: 'Africa/Casablanca', city: 'Marrakech', country: 'Morocco' },
  { timeZoneId: 'Africa/Dar_es_Salaam', city: 'Zanzibar', country: 'Tanzania' },
  { timeZoneId: 'Africa/Johannesburg', city: 'Cape Town', country: 'South Africa' },
  { timeZoneId: 'Africa/Johannesburg', city: 'Durban', country: 'South Africa' },
  { timeZoneId: 'Africa/Johannesburg', city: 'Pretoria', country: 'South Africa' },
  { timeZoneId: 'Africa/Khartoum', city: 'Omdurman', country: 'Sudan' },
  { timeZoneId: 'Africa/Lagos', city: 'Abuja', country: 'Nigeria' },
  { timeZoneId: 'Africa/Lagos', city: 'Kano', country: 'Nigeria' },
  { timeZoneId: 'Africa/Nairobi', city: 'Mombasa', country: 'Kenya' },
  { timeZoneId: 'Africa/Tripoli', city: 'Benghazi', country: 'Libya' },
  {
    timeZoneId: 'America/Anchorage',
    city: 'Fairbanks',
    district: 'Alaska',
    country: 'United States',
  },
  { timeZoneId: 'America/Asuncion', city: 'Ciudad del Este', country: 'Paraguay' },
  { timeZoneId: 'America/Bogota', city: 'Medellin', country: 'Colombia' },
  { timeZoneId: 'America/Bogota', city: 'Cali', country: 'Colombia' },
  { timeZoneId: 'America/Caracas', city: 'Maracaibo', country: 'Venezuela' },
  { timeZoneId: 'America/Chicago', city: 'Austin', district: 'Texas', country: 'United States' },
  { timeZoneId: 'America/Chicago', city: 'Dallas', district: 'Texas', country: 'United States' },
  { timeZoneId: 'America/Chicago', city: 'Houston', district: 'Texas', country: 'United States' },
  {
    timeZoneId: 'America/Chicago',
    city: 'Kansas City',
    district: 'Missouri',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Chicago',
    city: 'Minneapolis',
    district: 'Minnesota',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Chicago',
    city: 'Nashville',
    district: 'Tennessee',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Chicago',
    city: 'New Orleans',
    district: 'Louisiana',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Chicago',
    city: 'St Louis',
    district: 'Missouri',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Denver',
    city: 'Albuquerque',
    district: 'New Mexico',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Denver',
    city: 'Colorado Springs',
    district: 'Colorado',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Denver',
    city: 'Salt Lake City',
    district: 'Utah',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Denver',
    city: 'Santa Fe',
    district: 'New Mexico',
    country: 'United States',
  },
  { timeZoneId: 'America/Guayaquil', city: 'Quito', country: 'Ecuador' },
  { timeZoneId: 'America/La_Paz', city: 'Santa Cruz', country: 'Bolivia' },
  { timeZoneId: 'America/Lima', city: 'Arequipa', country: 'Peru' },
  { timeZoneId: 'America/Lima', city: 'Cusco', country: 'Peru' },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'Las Vegas',
    district: 'Nevada',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'Portland',
    district: 'Oregon',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'Sacramento',
    district: 'California',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'San Diego',
    district: 'California',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'San Francisco',
    district: 'California',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Los_Angeles',
    city: 'Seattle',
    district: 'Washington',
    country: 'United States',
  },
  {
    timeZoneId: 'America/Mexico_City',
    city: 'Guadalajara',
    district: 'Jalisco',
    country: 'Mexico',
  },
  { timeZoneId: 'America/Mexico_City', city: 'Puebla', district: 'Puebla', country: 'Mexico' },
  {
    timeZoneId: 'America/Mexico_City',
    city: 'Queretaro',
    district: 'Queretaro',
    country: 'Mexico',
  },
  { timeZoneId: 'America/Montevideo', city: 'Punta del Este', country: 'Uruguay' },
  {
    timeZoneId: 'America/New_York',
    city: 'Atlanta',
    district: 'Georgia',
    country: 'United States',
  },
  {
    timeZoneId: 'America/New_York',
    city: 'Boston',
    district: 'Massachusetts',
    country: 'United States',
  },
  {
    timeZoneId: 'America/New_York',
    city: 'Charlotte',
    district: 'North Carolina',
    country: 'United States',
  },
  { timeZoneId: 'America/New_York', city: 'Miami', district: 'Florida', country: 'United States' },
  {
    timeZoneId: 'America/New_York',
    city: 'Orlando',
    district: 'Florida',
    country: 'United States',
  },
  {
    timeZoneId: 'America/New_York',
    city: 'Philadelphia',
    district: 'Pennsylvania',
    country: 'United States',
  },
  {
    timeZoneId: 'America/New_York',
    city: 'Pittsburgh',
    district: 'Pennsylvania',
    country: 'United States',
  },
  {
    timeZoneId: 'America/New_York',
    city: 'Washington DC',
    district: 'District of Columbia',
    country: 'United States',
    searchTerms: ['DC'],
  },
  { timeZoneId: 'America/Phoenix', city: 'Tucson', district: 'Arizona', country: 'United States' },
  { timeZoneId: 'America/Santiago', city: 'Valparaiso', country: 'Chile' },
  { timeZoneId: 'America/Santo_Domingo', city: 'Punta Cana', country: 'Dominican Republic' },
  { timeZoneId: 'America/Sao_Paulo', city: 'Belo Horizonte', country: 'Brazil' },
  { timeZoneId: 'America/Sao_Paulo', city: 'Brasilia', country: 'Brazil' },
  { timeZoneId: 'America/Sao_Paulo', city: 'Rio de Janeiro', country: 'Brazil' },
  { timeZoneId: 'America/Sao_Paulo', city: 'Salvador', country: 'Brazil' },
  { timeZoneId: 'America/Toronto', city: 'Montreal', district: 'Quebec', country: 'Canada' },
  { timeZoneId: 'America/Toronto', city: 'Ottawa', district: 'Ontario', country: 'Canada' },
  { timeZoneId: 'America/Toronto', city: 'Quebec City', district: 'Quebec', country: 'Canada' },
  {
    timeZoneId: 'America/Vancouver',
    city: 'Victoria',
    district: 'British Columbia',
    country: 'Canada',
  },
  {
    timeZoneId: 'America/Regina',
    city: 'Saskatoon',
    district: 'Saskatchewan',
    country: 'Canada',
  },
  { timeZoneId: 'America/Edmonton', city: 'Calgary', district: 'Alberta', country: 'Canada' },
  { timeZoneId: 'America/Halifax', city: 'Moncton', district: 'New Brunswick', country: 'Canada' },
  { timeZoneId: 'America/Argentina/Buenos_Aires', city: 'Rosario', country: 'Argentina' },
  { timeZoneId: 'Asia/Amman', city: 'Aqaba', country: 'Jordan' },
  { timeZoneId: 'Asia/Baghdad', city: 'Basra', country: 'Iraq' },
  { timeZoneId: 'Asia/Bahrain', city: 'Manama', country: 'Bahrain' },
  { timeZoneId: 'Asia/Bangkok', city: 'Chiang Mai', country: 'Thailand' },
  { timeZoneId: 'Asia/Bangkok', city: 'Phuket', country: 'Thailand' },
  { timeZoneId: 'Asia/Colombo', city: 'Kandy', country: 'Sri Lanka' },
  { timeZoneId: 'Asia/Dhaka', city: 'Chittagong', country: 'Bangladesh' },
  { timeZoneId: 'Asia/Dubai', city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { timeZoneId: 'Asia/Dubai', city: 'Sharjah', country: 'United Arab Emirates' },
  { timeZoneId: 'Asia/Ho_Chi_Minh', city: 'Hanoi', country: 'Vietnam' },
  { timeZoneId: 'Asia/Ho_Chi_Minh', city: 'Da Nang', country: 'Vietnam' },
  { timeZoneId: 'Asia/Jakarta', city: 'Bandung', country: 'Indonesia' },
  { timeZoneId: 'Asia/Jakarta', city: 'Medan', country: 'Indonesia' },
  { timeZoneId: 'Asia/Jakarta', city: 'Surabaya', country: 'Indonesia' },
  { timeZoneId: 'Asia/Jerusalem', city: 'Haifa', country: 'Israel' },
  { timeZoneId: 'Asia/Jerusalem', city: 'Tel Aviv', country: 'Israel' },
  { timeZoneId: 'Asia/Karachi', city: 'Islamabad', country: 'Pakistan' },
  { timeZoneId: 'Asia/Karachi', city: 'Lahore', country: 'Pakistan' },
  { timeZoneId: 'Asia/Kathmandu', city: 'Pokhara', country: 'Nepal' },
  { timeZoneId: 'Asia/Kolkata', city: 'Ahmedabad', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Bangalore', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Chennai', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Delhi', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Hyderabad', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Jaipur', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Mumbai', country: 'India' },
  { timeZoneId: 'Asia/Kolkata', city: 'Pune', country: 'India' },
  { timeZoneId: 'Asia/Kuala_Lumpur', city: 'Johor Bahru', country: 'Malaysia' },
  { timeZoneId: 'Asia/Kuala_Lumpur', city: 'Penang', country: 'Malaysia' },
  { timeZoneId: 'Asia/Makassar', city: 'Denpasar', country: 'Indonesia' },
  { timeZoneId: 'Asia/Manila', city: 'Cebu', country: 'Philippines' },
  { timeZoneId: 'Asia/Manila', city: 'Davao', country: 'Philippines' },
  { timeZoneId: 'Asia/Riyadh', city: 'Jeddah', country: 'Saudi Arabia' },
  { timeZoneId: 'Asia/Riyadh', city: 'Mecca', country: 'Saudi Arabia' },
  { timeZoneId: 'Asia/Seoul', city: 'Busan', country: 'South Korea' },
  { timeZoneId: 'Asia/Seoul', city: 'Daegu', country: 'South Korea' },
  { timeZoneId: 'Asia/Seoul', city: 'Incheon', country: 'South Korea' },
  { timeZoneId: 'Asia/Shanghai', city: 'Beijing', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Chengdu', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Chongqing', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Guangzhou', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Hangzhou', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Shenzhen', country: 'China' },
  { timeZoneId: 'Asia/Shanghai', city: 'Wuhan', country: 'China' },
  { timeZoneId: 'Asia/Taipei', city: 'Kaohsiung', country: 'Taiwan' },
  { timeZoneId: 'Asia/Taipei', city: 'Taichung', country: 'Taiwan' },
  { timeZoneId: 'Asia/Tehran', city: 'Mashhad', country: 'Iran' },
  { timeZoneId: 'Asia/Tokyo', city: 'Fukuoka', country: 'Japan' },
  { timeZoneId: 'Asia/Tokyo', city: 'Kyoto', country: 'Japan' },
  { timeZoneId: 'Asia/Tokyo', city: 'Nagoya', country: 'Japan' },
  { timeZoneId: 'Asia/Tokyo', city: 'Osaka', country: 'Japan' },
  { timeZoneId: 'Asia/Tokyo', city: 'Sapporo', country: 'Japan' },
  { timeZoneId: 'Australia/Brisbane', city: 'Gold Coast', country: 'Australia' },
  { timeZoneId: 'Australia/Brisbane', city: 'Sunshine Coast', country: 'Australia' },
  { timeZoneId: 'Australia/Hobart', city: 'Launceston', country: 'Australia' },
  { timeZoneId: 'Australia/Melbourne', city: 'Geelong', country: 'Australia' },
  { timeZoneId: 'Australia/Perth', city: 'Fremantle', country: 'Australia' },
  { timeZoneId: 'Australia/Sydney', city: 'Canberra', country: 'Australia' },
  { timeZoneId: 'Australia/Sydney', city: 'Newcastle', country: 'Australia' },
  { timeZoneId: 'Europe/Amsterdam', city: 'Eindhoven', country: 'Netherlands' },
  { timeZoneId: 'Europe/Amsterdam', city: 'Rotterdam', country: 'Netherlands' },
  { timeZoneId: 'Europe/Amsterdam', city: 'The Hague', country: 'Netherlands' },
  { timeZoneId: 'Europe/Athens', city: 'Thessaloniki', country: 'Greece' },
  { timeZoneId: 'Europe/Berlin', city: 'Cologne', country: 'Germany' },
  { timeZoneId: 'Europe/Berlin', city: 'Frankfurt', country: 'Germany' },
  { timeZoneId: 'Europe/Berlin', city: 'Hamburg', country: 'Germany' },
  { timeZoneId: 'Europe/Berlin', city: 'Munich', country: 'Germany' },
  { timeZoneId: 'Europe/Berlin', city: 'Stuttgart', country: 'Germany' },
  { timeZoneId: 'Europe/Brussels', city: 'Antwerp', country: 'Belgium' },
  { timeZoneId: 'Europe/Brussels', city: 'Ghent', country: 'Belgium' },
  { timeZoneId: 'Europe/Budapest', city: 'Debrecen', country: 'Hungary' },
  { timeZoneId: 'Europe/Budapest', city: 'Szeged', country: 'Hungary' },
  { timeZoneId: 'Europe/Copenhagen', city: 'Aarhus', country: 'Denmark' },
  { timeZoneId: 'Europe/Copenhagen', city: 'Odense', country: 'Denmark' },
  { timeZoneId: 'Europe/Dublin', city: 'Cork', country: 'Ireland' },
  { timeZoneId: 'Europe/Dublin', city: 'Galway', country: 'Ireland' },
  { timeZoneId: 'Europe/Helsinki', city: 'Tampere', country: 'Finland' },
  { timeZoneId: 'Europe/Helsinki', city: 'Turku', country: 'Finland' },
  { timeZoneId: 'Europe/Istanbul', city: 'Ankara', country: 'Turkey' },
  { timeZoneId: 'Europe/Istanbul', city: 'Izmir', country: 'Turkey' },
  { timeZoneId: 'Europe/Lisbon', city: 'Porto', country: 'Portugal' },
  { timeZoneId: 'Europe/London', city: 'Birmingham', country: 'United Kingdom' },
  { timeZoneId: 'Europe/London', city: 'Edinburgh', country: 'United Kingdom' },
  { timeZoneId: 'Europe/London', city: 'Glasgow', country: 'United Kingdom' },
  { timeZoneId: 'Europe/London', city: 'Liverpool', country: 'United Kingdom' },
  { timeZoneId: 'Europe/London', city: 'Manchester', country: 'United Kingdom' },
  { timeZoneId: 'Europe/Madrid', city: 'Barcelona', country: 'Spain' },
  { timeZoneId: 'Europe/Madrid', city: 'Bilbao', country: 'Spain' },
  { timeZoneId: 'Europe/Madrid', city: 'Seville', country: 'Spain' },
  { timeZoneId: 'Europe/Madrid', city: 'Valencia', country: 'Spain' },
  { timeZoneId: 'Europe/Moscow', city: 'Saint Petersburg', country: 'Russia' },
  { timeZoneId: 'Europe/Oslo', city: 'Bergen', country: 'Norway' },
  { timeZoneId: 'Europe/Oslo', city: 'Trondheim', country: 'Norway' },
  { timeZoneId: 'Europe/Paris', city: 'Bordeaux', country: 'France' },
  { timeZoneId: 'Europe/Paris', city: 'Lyon', country: 'France' },
  { timeZoneId: 'Europe/Paris', city: 'Marseille', country: 'France' },
  { timeZoneId: 'Europe/Paris', city: 'Nice', country: 'France' },
  { timeZoneId: 'Europe/Paris', city: 'Toulouse', country: 'France' },
  { timeZoneId: 'Europe/Prague', city: 'Brno', country: 'Czech Republic' },
  { timeZoneId: 'Europe/Prague', city: 'Ostrava', country: 'Czech Republic' },
  { timeZoneId: 'Europe/Rome', city: 'Florence', country: 'Italy' },
  { timeZoneId: 'Europe/Rome', city: 'Milan', country: 'Italy' },
  { timeZoneId: 'Europe/Rome', city: 'Naples', country: 'Italy' },
  { timeZoneId: 'Europe/Rome', city: 'Turin', country: 'Italy' },
  { timeZoneId: 'Europe/Rome', city: 'Venice', country: 'Italy' },
  { timeZoneId: 'Europe/Stockholm', city: 'Gothenburg', country: 'Sweden' },
  { timeZoneId: 'Europe/Stockholm', city: 'Malmo', country: 'Sweden' },
  { timeZoneId: 'Europe/Vienna', city: 'Graz', country: 'Austria' },
  { timeZoneId: 'Europe/Vienna', city: 'Salzburg', country: 'Austria' },
  { timeZoneId: 'Europe/Warsaw', city: 'Gdansk', country: 'Poland' },
  { timeZoneId: 'Europe/Warsaw', city: 'Krakow', country: 'Poland' },
  { timeZoneId: 'Europe/Warsaw', city: 'Wroclaw', country: 'Poland' },
  { timeZoneId: 'Europe/Zurich', city: 'Basel', country: 'Switzerland' },
  { timeZoneId: 'Europe/Zurich', city: 'Geneva', country: 'Switzerland' },
  { timeZoneId: 'Pacific/Auckland', city: 'Christchurch', country: 'New Zealand' },
  { timeZoneId: 'Pacific/Auckland', city: 'Queenstown', country: 'New Zealand' },
  { timeZoneId: 'Pacific/Auckland', city: 'Wellington', country: 'New Zealand' },
  { timeZoneId: 'Pacific/Port_Moresby', city: 'Lae', country: 'Papua New Guinea' },
  { timeZoneId: 'Europe/Tallinn', city: 'Tallinn', country: 'Estonia', primary: true },
  { timeZoneId: 'Europe/Riga', city: 'Riga', country: 'Latvia', primary: true },
  { timeZoneId: 'Europe/Vilnius', city: 'Vilnius', country: 'Lithuania', primary: true },
  { timeZoneId: 'Europe/Belgrade', city: 'Belgrade', country: 'Serbia', primary: true },
  { timeZoneId: 'Europe/Zagreb', city: 'Zagreb', country: 'Croatia', primary: true },
  { timeZoneId: 'Europe/Ljubljana', city: 'Ljubljana', country: 'Slovenia', primary: true },
  { timeZoneId: 'Europe/Bratislava', city: 'Bratislava', country: 'Slovakia', primary: true },
  { timeZoneId: 'America/Puerto_Rico', city: 'San Juan', country: 'Puerto Rico', primary: true },
  { timeZoneId: 'America/Monterrey', city: 'Monterrey', country: 'Mexico', primary: true },
  { timeZoneId: 'Asia/Tbilisi', city: 'Tbilisi', country: 'Georgia', primary: true },
  { timeZoneId: 'Asia/Yerevan', city: 'Yerevan', country: 'Armenia', primary: true },
  { timeZoneId: 'Asia/Baku', city: 'Baku', country: 'Azerbaijan', primary: true },
  { timeZoneId: 'Asia/Tashkent', city: 'Tashkent', country: 'Uzbekistan', primary: true },
  { timeZoneId: 'Asia/Bishkek', city: 'Bishkek', country: 'Kyrgyzstan', primary: true },
  { timeZoneId: 'Asia/Dushanbe', city: 'Dushanbe', country: 'Tajikistan', primary: true },
  { timeZoneId: 'Asia/Ulaanbaatar', city: 'Ulaanbaatar', country: 'Mongolia', primary: true },
  { timeZoneId: 'Africa/Luanda', city: 'Luanda', country: 'Angola', primary: true },
  { timeZoneId: 'Africa/Maputo', city: 'Maputo', country: 'Mozambique', primary: true },
  { timeZoneId: 'Africa/Kampala', city: 'Kampala', country: 'Uganda', primary: true },
  { timeZoneId: 'Africa/Kigali', city: 'Kigali', country: 'Rwanda', primary: true },
  { timeZoneId: 'Africa/Harare', city: 'Harare', country: 'Zimbabwe', primary: true },
  { timeZoneId: 'Africa/Lusaka', city: 'Lusaka', country: 'Zambia', primary: true },
  { timeZoneId: 'Africa/Gaborone', city: 'Gaborone', country: 'Botswana', primary: true },
];
